### PR TITLE
LOBDBase Expansion

### PR DESCRIPTION
**Pull request by j-e-hunter**
Added MAG, DAG, LysoIP_DAGs, Cholesterol/Coprostanols and esters, Astaxanthin, Bile Salts, Support for 2H and 13C Isotopes.
Updated default database, componentcomptable and adduct hierarchies objects.
Updated inst xlsx and csv files.
Updated generateLOBDbase function.

### CODE REVIEW

**Comment by jamesrco** [comment]
I see a couple of minor housekeeping issues here... misspelling (ChlorestorolAcetate) and then some of the comments that precede the new checks for the m_D and m_C_thirteen columns still reference silicon. Also, check that you are not going over the Bioc style line width and are manually breaking lines as needed... lines 164-165, 274, maybe others. The former will require everything to be regenerated I think... but better to get it right now. I don't have time to fix this week, maybe one of you guys can take a stab at it?

Jon, awesome work -- this is very exciting!

**Comment by j-e-hunter** [comment]
OK thanks for the input, I will pick this up again in a few days as I have some pressing other work.

**Comment by j-e-hunter** [comment]
OK i've made the updates Jamie suggested and resolved the conflicts with the main branch. Not sure how to wrangle github into accepting it so I'l leave that to you guys. Let me know if you need me to do anything else with this.

**Comment by lee-t** [comment]
Resolved branch conflicts and merged. Ask me to revert if still not up to standards with regards to nomenclature; this addition seems to not interrupt normal usage in testing.

**Comment by jamesrco** [comment]
@lee-t: There are some git tags that got stuck in the merged version of at least one of the files.

**Comment by jamesrco** [comment]
Also, "ChloresterolAcetate" is still misspelled.

**Comment by jamesrco** [comment]
I am worried about this one. It seems the branch which was merged was not fully current with master when it was merged... and a manual attempt to bring the two into sync was then made.

**Comment by jamesrco** [comment]
Code will not execute or compile as is. I am trying to fix.

**Comment by jamesrco** [comment]
I am receiving errors when testing the generateLOBdbase function. Trying to fix.

**Comment by jamesrco** [comment]
Okay this is all a big mess... there are multiple versions of the helper functions in the generateLOBdbase.R file now... as a result of the improper conflict resolution. I'm going to try and roll everything back.

**Comment by j-e-hunter** [comment]
Hi guys, I'd be interested to hear what went wrong here. Cholesterol Acetate was indeed corrected and the thing ran fine for me during testing. I suspect that something got screwy with my use of github. Maybe we can discuss at the next lobstahs skype?

**Comment by jamesrco** [comment]
Yeah, we should recap. None of it a big deal, but certainly some lessons learned. It was one of those situations in which a bunch of minor oversights (and the confusion that ensures from a multi-way collaboration) came together to create a headache. Thankfully we are using version control, which is designed exactly for rolling back changes and then providing a means to get things on track again.

**Comment by jamesrco** [comment]
All in all, great work @j-e-hunter and @lee-t !

**Pull request merged**
